### ISSUE TITLE
Deploy your website and add to the documentation

### ISSUE THREAD

**Issue by AbbeyIT** [TheBaljitSingh/portfolio-website#1]
You can deploy your website here on GitHub and add the link in the documentation for people to see your work.

**Comment by TheBaljitSingh** [comment]
I have deployed website check this 
And help me for documentation 
https://thebaljitsingh.github.io/portfolio/

**Comment by AbbeyIT** [comment]
Assign this issue to me @TheBaljitSingh

**Comment by TheBaljitSingh** [comment]
Assigned
